# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'
 
use_frameworks!
workspace 'Modularization'
 
target 'TMDb' do
  # Pods for TMDb
end
 
target 'Favorite' do
  project '../Favorite/Favorite'
end